name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINUX_UBUNTU_SERVER_IP }}
        username: ${{ secrets.LINUX_UBUNTU_SERVER_USERNAME }}
        password: ${{ secrets.LINUX_UBUNTU_SERVER_PASSWORD }}
        port: 22
        script: |
          echo "truy cập vào đường dẫn file server"
          cd /var/www/blade_travel_server
          echo "pull dữ liệu mới trên github"
          git pull
          git status
          echo "kích hoạt kiểm tra nvm"
          . $HOME/.nvm/nvm.sh
          nvm use
          echo "cài đặt lại node module"
          npm ci
          echo "build dự án"
          npm run build
          echo "reset SWAP"
          sudo swapoff -a; sudo swapon -a
          echo "Gửi thông báo"
          curl -X POST -H "Content-Type: application/json" -H "Authorization:${{ secrets.DISCORD_AUTHORIZATION }}" -d '{"content":"Dự án server VIP đã deploy thành công link: https://api.myblade.io.vn/api/v1 "}' ${{ secrets.DISCORD_NOTIFY_URL }}
